name: HerokuContainer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checking env
      run: ls

    - uses: actions/checkout@master
    - name: Build the tagged Docker image
      run: docker build . --file HerokuCICD/Dockerfile --tag ${{ secrets.HEROKU_APP_NAME }}
    
    - name: Tag Docker image
      run: docker tag ${{ secrets.HEROKU_APP_NAME }} registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
    
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

    - name: Push container
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        ASPNETCORE_ENVIRONMENT: Development
      run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web